---
- ansible.builtin.import_tasks:
    file: sssd.yml
  tags:
    - sssd
- ansible.builtin.import_tasks:
    file: ceph.yml
  tags:
    - ceph
- ansible.builtin.import_tasks:
    file: slurm.yml
  tags:
    - slurm

- ansible.builtin.import_tasks:
    file: slurm_drmaa.yml
  tags:
    - slurm_drmaa